### ISSUE TITLE
Remove upper pinning for flake 8 and add test for flake8 main

### ISSUE THREAD

**Issue by avylove** [john-hen/Flake8-pyproject#14]
When flake8 moved to 6.0, pip decided version 0.9.0 was the only one that would meet the requirements since the version was pinned in 0.9.1. Since the configuration loading is different in that version, the config was ignored. You fixed this a couple days later so thanks for addressing it quickly. However, removing the pinning of flake8 < 7 would be better because when flake8 7 comes out it's more likely to work with the latest version than with 0.9.0, which is what will get pulled otherwise.

It would also be good to add a CI test that runs against flake8 main. The test could be non-critical with the continue-on-error option or not. This way there would be heads-up about any breaking behavior coming down the line.

**Comment by john-hen** [comment]
That makes sense, thanks for elaborating on that. You want to do the PR? (I like adding contributors.) First thing is any easy change, and I can merge and release that quickly. The CI test probably takes a little more thought.
