### ISSUE TITLE
Flake8-pyproject doesn't work with flake8 `6.1.0`

### ISSUE THREAD

**Issue by elevans** [john-hen/Flake8-pyproject#22]
`flake8` version `6.1.0` was recently released on conda forge but unfortunately seems to be incompatible with `flake8-pyproject` version `1.2.3`. With version `6.1.0` my configuration in my `pyproject.toml` are ignored. Downgrading to `6.0.0` resolves this issue.

**Comment by john-hen** [comment]
I don't see that in the nightly tests. The [first run with Flake8 6.1.0](https://github.com/john-hen/Flake8-pyproject/actions/runs/5703696093) (three days ago) as well as all subsequent runs passed, just like the [last run with Flake8 6.0.0](https://github.com/john-hen/Flake8-pyproject/actions/runs/5697906226).

I also cannot reproduce that locally: with Python 3.11, Flake8 6.1.0, Flake8-pyproject 1.2.3, on Windows. Though everything is installed directly via Pip, not Conda.

**Comment by elevans** [comment]
Hi @john-hen,

Thanks for the quick reply. I went back and tested again and things seem to be okay with `6.1.0`. Our CI jobs were failing and it was pointing in this direction...but clearly that was wrong! Sorry about that. I'm closing this issue.

Cheers,

-Ed
