### ISSUE TITLE
`flake8p` is only aware of `pyproject.toml` in the current folder

### ISSUE THREAD

**Issue by john-hen** [john-hen/Flake8-pyproject#7]
As I've noticed today, when running `flake8p` in a folder below the main project folder, it does not pull the configuration from `pyproject.toml` (then in a folder or more above). This used to work before, so is due to the refactoring in Flake8 version 5 and the new "hook" tailored to that. Mea culpa. This should be fixed, somehow.

As of now, `flake8p` only works as expected when run from the folder that contains `pyproject.toml`. The existing test cases all assume that simple folder structure, so a test case should be added that tests running from a subfolder.

**Comment by john-hen** [comment]
On second thought, I'm actually fine with this behavior. That's what [Mypy] does, and [Pylint] as well. And pyTest we'd also typically run from the project folder. CI workflows are always set up that way. And it makes sense that when we configure a tool for a specific project in `pyproject.toml`, we would run that tool in that very project folder.

So I won't fix this, as it keeps things simple and wouldn't add much otherwise. Yes, it's different from what Flake8 does, but then Flake8 does not support `pyproject.toml`. 🤷

[Mypy]: https://mypy.readthedocs.io/en/stable/config_file.html
[Pylint]: https://pylint.pycqa.org/en/latest/user_guide/usage/run.html

**Comment by rixx** [comment]
Are you open to reconsidering this? I frequently run various linters from subdirectories within the project as I'm developing, and it would be handy to be able to do this while also using `pyproject.toml` for configuration. Happy to contribute a patch for this.

**Comment by john-hen** [comment]
Hi. Can't you use the `--toml-config` command-line option? It was added after this issue here was closed. So with a little more typing, and knowing the relative path to `pyproject.toml`, this should already be possible.

As for a patch, I'd say as a rule of thumb: If it doubles the lines of code, then rather not. Otherwise it's fine.

**Comment by rixx** [comment]
Alright thanks, I can use a private wrapper script that finds the nearest pyproject.toml and passes it to `--toml-config`, then, if I'm the only one with this problem. (Since the goal is to do less typing and more linting whenever and whereever :wink: )
